defaults: &defaults
  username: root
  password:
  adapter:  mysql2
  host:     localhost
  socket: /tmp/mysql.sock

# replace the above login details with information from ./config/dblogin.yml
<%= file = File.join(RAILS_ROOT, "config", "dblogin.yml")
    IO.read(file) if File.exist?(file) %>

development:
  <<: *defaults
  database: seanchai_dev

test:
  <<: *defaults
  database: seancha_test

production:
  <<: *defaults
  database: seanchai_prod